# On 12/21/16 these runs fail.
# Problem 1:  there are problems in combining -p ?? with -L ??.
# See the notes/12_21_16  for a work-around.
# Problem 2:  There are unresolved bugs in experiments/hyptest.jl
#!/usr/bin/bash
# The following should run without errors.  

# No checking for correct results is done in this version.
# However, the final csv file generated by hyptest.jl can be compared with 
#    the files in experiments/configs/correct_results

cd ../experiments

julia -L simulation.jl run.jl configs/example1
julia hyptest.jl configs/example1

julia -L simulation.jl run.jl configs/example2
julia hyptest.jl configs/example2

julia -L simulation.jl run.jl configs/example3
julia hyptest.jl configs/example3

julia -L simulation.jl run.jl configs/example4
julia hyptest.jl configs/example4

julia -L simulation.jl run.jl configs/example5
julia hyptest.jl configs/example5

julia -L simulation.jl run.jl configs/T100_pow_neg_n70_pm1
julia significance.jl configs/T100_pow_neg_n70_pm1
julia hyptest.jl configs/T100_pow_neg_n70_pm1

julia -L simulation.jl run.jl configs/T100_pow_neg_n50_pm1
julia significance.jl configs/T100_pow_neg_n50_pm1
julia hyptest.jl configs/T100_pow_neg_n50_pm1


cd ../test
