# On 12/21/16 these runs fail.
# Problem 1:  there are problems in combining -p ?? with -L ??.
# See the notes/12_21_16  for a work-around.
# Problem 2:  There are unresolved bugs in experiments/hyptest.jl
#!/usr/bin/bash
# The following should run without errors.  

# No checking for correct results is done in this version.
# However, the final csv file generated by hyptest.jl can be compared with 
#    the files in experiments/configs/correct_results

cd ../experiments

julia n_neutral.jl configs/nn_example

julia n_neutral.jl configs/nn_example3

julia n_neutral.jl nn_configs/nn_example1

julia n_neutral.jl nn_configs/nn_example2

julia n_infsites.jl configs/in_example1

julia n_infsites.jl configs/in_example2

julia n_infsites.jl nn_configs/nn_het_ratio


cd ../test
